[toolchain]
anchor_version = "0.31.1"

[features] 
resolution = true
skip-lint = false

[programs.localnet]
sol_chain = "FqNejJjmQcntD1SQB9zAEUD8k6HymXwUBoXuBgWsW3eg"

[programs.devnet]
sol_chain = "FqNejJjmQcntD1SQB9zAEUD8k6HymXwUBoXuBgWsW3eg"

[registry]
url = "https://api.apr.dev"

# [provider]
# cluster = "devnet"
# wallet = "~/.config/solana/bolt.json"
# anchor test --skip-local-validator


[provider]
cluster = "Localnet"
wallet = "/Users/pritam/.config/solana/bolt.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"