[toolchain]
anchor_version = "0.31.1"

[features] 
resolution = true
skip-lint = false

[programs.localnet]
sol_chain = "dCVdEWu3XaGhDy7wXBzgcUYk1nk43Xe1NK2PfAKATqo"

[registry]
url = "https://api.apr.dev"

# [provider]
# cluster = "devnet"
# wallet = "~/.config/solana/bolt.json"

[provider]
cluster = "devnet"
wallet = "/Users/pritam/.config/solana/bolt.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"